name: Update News

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}
      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: print log
        run: echo "こんにちは"
      - name: Install Libraries
        run: |
          echo `node -v`
          npm install
      - name: update news
        run: |
          node App.js
