name: Update News

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}
      - name: set up ImageMagick Action
        uses: jruipinto/ImageMagick-action@v1
      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: print log
        run: echo "こんにちは"
      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - name: Install Libraries
        run: |
          echo `node -v`
          npm install
      - name: Create branch
        run: |
          git switch -c update/news_${{ env.CURRENT_DATETIME }}
          git branch
      - name: update news
        run: |
          node App5.js
      - name: compression images
        run: |
          mv src/tmp/*.jpg src/image
          mogrify -path src/image/ -format jpg src/tmp/*.png
          mogrify src/image/*.jpg -strip -quality 30 -colorspace sRGB
          rm -rf src/tmp
      - name: Set up Git user
        run: |
          git config user.email "${USERNAME}@users.noreply.github.com"
          git config user.name "${USERNAME}"
        env:
          USERNAME: ${{ github.actor }}
      - name: git commit
        run: |
          git add .
          git commit --author="$AUTHOR" -m "Update News"
          git log --oneline 
          git branch
      - name: git push
        run: |
          git push origin -u update/news_${{ env.CURRENT_DATETIME }}
      - name: Create Release Pull Request
        run: |
          gh pr create -B main --title "Update News" --body "プルリクエストを作るテスト" --head update/news_${{ env.CURRENT_DATETIME }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTHOR: ${{ github.event.pusher.name }}
