name: Update News

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}
      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: print log
        run: echo "こんにちは"
      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Install Libraries
        run: |
          echo `node -v`
          npm install
      - name: update news
        run: |
          node App.js
      - name: Create branch
        run: |
          git switch -c update/news_${{ env.CURRENT_DATETIME }}
      - name: Create Release Pull Request
        run: |
          gh pr create -B main --title "Update News" --body "プルリクエストを作るテスト" --head "foo"
